server:
  port: 80

spring:
  application:
    name: cloud-order-consumer-openfeign

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心
    fetch-registry: true
    service-url:
      #设置与eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
logging:
  level:
    com.markfish.springcloud.service.PaymentFeignService: debug
