server:
  port: 8005

spring:
  application:
    name: cloud-payment-hystrix-service


eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心
    fetch-registry: true
    service-url:
      #设置与eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: payment8005 # 在eureka取别名
    prefer-ip-address: true  #访问路径可以显示ip地址
